version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bradhe/blobd
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: setup
          command: |
            make setup
      - run:
          name: test
          command: |
            make test
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make release
            fi
