version: 2
jobs:
  build:
    working_directory: /go/src/github.com/bradhe/blobd
    docker:
      - image: circleci/golang:1.11-node
    steps:
      - checkout
      - setup_remote_docker
      - run: go get -u github.com/jteeuwen/go-bindata/...
      - run: cd ./server/ui && npm install
      - run: make test
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
              make release
            fi
